@startuml
'https://plantuml.com/sequence-diagram

class Solution43
{
    +{static}Solution43 : main()
    -{static}Solution43 : input()
    -{static}Solution43 : jsFolder(String path)
    -{static}Solution43 : cssFolder(String path)
    -{static}Solution43 : createHTMLFile(String siteName, String author, String path)
}

@enduml